### ISSUE TITLE
Build and distribute gridcoin package for Debian

### ISSUE THREAD

**Issue by scotte** [caraka/gridcoin-packaging#1]
Hi @caraka - I don't know if this repo is current, or the right place to discuss this, but I'll give it a try.

Would you be open to building and distributing official gridcoin packages for Debian? I would be willing to help take on this task (as I run Debian all over the place, including where my wallet runs). The packages could be distributed via bintray, which will do free package repository hosting for open source projects. There's also finding the right CI approach for the builds.

I'm also well aware of the security consequences and would expect the core gridcoin team to help with those bits (signing keys, trust, etc - all huge things, especially with a cryptocurrency).

The current "use the Ubuntu PPA and hack it up a bit" approach isn't great, for a number of reasons (frankendistros are inherently evil :-) ). Building from source is no problem for me, but signed binary packages are quite handy, and easier to upgrade.

Since I'm only a few weeks into using gridcoin, I'm sorry if these are all things that have already been discussed, planned, or intentionally not done - but if not, let me know what I can do to help.

**Comment by caraka** [comment]
Greetings scotte!
Sorry, I haven't looked at this repo in AGES!  It is totally out of date. However, as far as debian packaging goes, it is something that I have been tyre kicking for some time. I also had my first look at bintray just last week! I totally agree that the use the PPA and hack it is very poor. We shall talk more! I'll PM you on IRC

**Comment by scotte** [comment]
With https://bintray.com/gridcoin I think we can close this. Thanks again!
